#!/bin/sh

set -e

# Ensure initramfs directory exists
cd rust-module

# Build the kernel module
make KDIR=/usr/src/linux LLVM=1

# Install the kernel modules into initramfs directory
make KDIR=/usr/src/linux LLVM=1 INSTALL_MOD_PATH=../build/initramfs modules_install
