#!/bin/sh

set -e

cd linux

# Build the kernel
make -j`nproc` LLVM=1 all
make LLVM=1 SPHINXDIRS="rust"

# Copy the built kernel into build directory
cp arch/x86/boot/bzImage ../build/bzImage

# Install the kernel modules into initramfs directory
make LLVM=1 INSTALL_MOD_PATH=../build/initramfs modules_install
