#!/bin/sh

set -e

docker run --rm -it \
    -u $(id -u):$(id -g) \
    -v "`pwd`:/usr/src" \
    -w "/usr/src" \
    --network=host \
    docker.io/aboehm/clt2024-rust-on-linux-workshop:`uname -m` \
    $*
