#!/bin/sh

set -e

# Cleanup old files
rm -rf ./build/initramfs/lib/modules ./build/initramfs.cpio

# Build kernel and modules
./scripts/enter-build-env ./scripts/build-kernel

# Regenerate the initramfs
./scripts/enter-build-env ./scripts/gen-initramfs

# Run the kernel
./scripts/run-kernel
