#!/usr/bin/env bash

set -e

# Ensure initramfs directory exists
mkdir -p build/initramfs
cd build/initramfs

# Create directory layout
mkdir -p bin etc/init.d dev proc sbin sys usr/bin usr/sbin

# Install busybox
cp -f /usr/bin/busybox bin
bin/busybox --install bin

# Create a basic init script
cat >init <<EOF
#!/bin/sh

# Only sleep short time to wait for some debug messages
sleep 1

echo ""
echo "################################"
echo "# Starting into minimal rootfs #"
echo "################################"
echo ""

# Mount kernel filesystems
mount -t proc none /proc
mount -t sysfs none /sys

# Generate devices
/bin/mdev -s
echo /bin/mdev >/proc/sys/kernel/hotplug

echo "Loading minimal rust sample module via:"
echo ""
echo "  insmod lib/modules/\`uname -r\`/kernel/samples/rust/rust_minimal.ko"
echo ""
insmod lib/modules/\`uname -r\`/kernel/samples/rust/rust_minimal.ko

exec /bin/sh
EOF
chmod +x init

find . |cpio -H newc --owner 0:0 -o -O ../initramfs.cpio
