#!/usr/bin/env bash

set -e

# Ensure initramfs directory exists
mkdir -p initramfs
cd initramfs

# Create directory layout
mkdir -p bin etc dev proc sbin sys usr/bin usr/sbin

# Create some basic devices
[ -e dev/zero ] || sudo mknod -m 644 dev/zero b 1 3
[ -e dev/null ] || sudo mknod -m 644 dev/null b 1 5
[ -e dev/console ] || sudo mknod -m 644 dev/console c 5 1 
[ -e dev/loop0 ] || sudo mknod -m 644 dev/loop0 b 7 0

# Install busybox
cp -f /usr/bin/busybox bin
bin/busybox --install bin

# Create a basic init script
cat >init <<EOF
#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
exec /bin/sh
EOF
chmod +x init

find . |cpio -H newc --owner 0:0 -o -O ../initramfs.cpio
