#!/usr/bin/env bash

set -e

qemu-system-x86_64 \
    -monitor none \
    -serial stdio \
    --kernel linux/arch/x86_64/boot/bzImage \
    --initrd initramfs.cpio \
    --append "init=/sbin/init console=ttyS0" \
