#!/usr/bin/env bash

set -e

qemu-system-x86_64 \
    -monitor none \
    -serial stdio \
    --kernel build/bzImage \
    --initrd build/initramfs.cpio \
    --append "console=ttyS0 debug" \
    --vga none -display none # Disable this line to get a display output
