name: Image building of build environment

on:
  push:
    branches: [ "main" ]

jobs:
  build_environment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            docker_platform: linux/amd64
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.docker_platform }}
          file: docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/clt2024-rust-on-linux-workshop:${{ matrix.arch }}
