name: Build linux kernel

on:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    container: docker.io/aboehm/clt2024-rust-on-linux-workshop:x86_64
    steps:
      - uses: actions/checkout@v3

      - name: Build kernel
        run: |
          cd linux
          make -j`nproc` LLVM=1 all
