name: Build linux kernel

on:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    container: docker.io/aboehm/clt2024-rust-on-linux-workshop:x86_64
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Build kernel
        run: |
          cp linux-config/v6.7-rust-clt24 linux/.config
          cd linux
          make -j`nproc` LLVM=1 all
